package cn.lv.hgstudy.pojo;

// Generated 2017-3-19 22:02:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Playhistory generated by hbm2java
 */
public class StuAttention implements java.io.Serializable {

	private Integer attId;
	private String userId;
	private Integer couId;
	private Date creatTime;

	public StuAttention() {
	}

	public Integer getAttId() {
		return attId;
	}

	public void setAttId(Integer attId) {
		this.attId = attId;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Integer getCouId() {
		return couId;
	}

	public void setCouId(Integer couId) {
		this.couId = couId;
	}

	public Date getCreatTime() {
		return creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}
}
